#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Keboola\ScaffoldApp\Command\ImportOrchestrationCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ImportOrchestrationCommand());

$application->run();
